Adding web link convenience button to open a valid url value in a browser window.
comictagger/comictagger pull request #240
Opened 2022-03-31 17:04 UTC by MichaelFitzurka

resolves #239

2022-03-31 17:21 UTC, lordwelch requested changes

2022-03-31 17:21 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +            web_link = "{0}".format(self.leWebLink.text()).strip();
this can be shortened to `self.leWebLink.text().strip()`

2022-03-31 17:21 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +            if len(web_link) > 0:
You can also use `if web_link:` it's mostly equivalent and accounts for None values but shouldn't matter in this case

2022-03-31 17:21 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +                    response = requests.get(web_link)
This response isn't used.

2022-03-31 17:21 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +import requests
requests isn't actually used in this change

2022-03-31 17:36 UTC, MichaelFitzurka commented on comictaggerlib/taggerwindow.py
> +            web_link = "{0}".format(self.leWebLink.text()).strip();
done

2022-03-31 17:36 UTC, MichaelFitzurka commented on comictaggerlib/taggerwindow.py
> +                    response = requests.get(web_link)
done - removed variable.

2022-03-31 17:36 UTC, MichaelFitzurka commented on comictaggerlib/taggerwindow.py
> +import requests
It is used to validate the url.

2022-03-31 17:37 UTC, MichaelFitzurka commented on comictaggerlib/taggerwindow.py
> +            if len(web_link) > 0:
Done.

2022-04-01 04:13 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +import requests
urllib is in the standard library and has a parse method to validate URLs the code currently used actually makes a network request and then throws away the response which is not desirable

2022-04-01 13:53 UTC, MichaelFitzurka commented on comictaggerlib/taggerwindow.py
> +import requests
urlparse passes mangled urls like: **https://https://https://www.foo.bar** as valid.
But is good enough.
Changes made.

2022-04-02 19:32 UTC, lordwelch approved these changes

2022-04-02 22:43 UTC, merged