Adding source_name to add_issue_select_details.
comictagger/comictagger pull request #331
Opened 2022-07-11 13:58 UTC by MichaelFitzurka

Fixes #330

2022-07-11 18:04 UTC, lordwelch commented
The argument order is incorrect

2022-07-11 22:03 UTC, MichaelFitzurka commented
The code works as written.
Can you be more specific as to the “incorrect” order?

2022-07-11 22:05 UTC, lordwelch requested changes

2022-07-11 22:05 UTC, lordwelch commented on comictaggerlib/comiccacher.py
> +        issue_id: int,
Here you specifically have source_name, and then issue_id

2022-07-11 22:05 UTC, lordwelch commented on comictaggerlib/comicvinetalker.py
> +        cvc.add_issue_select_details(issue_id, self.source_name, image_url, thumb_url, cover_date, page_url)
Here you specifically have issue_id and then source_name

2022-07-12 13:13 UTC, MichaelFitzurka commented on comictaggerlib/comicvinetalker.py
> +        cvc.add_issue_select_details(issue_id, self.source_name, image_url, thumb_url, cover_date, page_url)
D'Oh! - It's that self in python's parameter list - throws off my count.

2022-07-12 14:31 UTC, merged