Preserve hidden metadata values when reading from GUI form
comictagger/comictagger pull request #693
Opened 2024-10-03 22:09 UTC by mizaki

Currently when `write_tags` is used, `form_to_metadata` is called within it which means any "hidden" values such as `data-origin`, `identifier`, `price`, `rights`, `issue_id`, `series_id`, `is_version_of` and `last_mark` are erased.

Some of these values are/may be of use to a tag plugin. (Saving the `issue_is` and `series_id` in ACBF for example.)

I'm not sure if doing it in the `form_to_metadata` will cause problems anywhere else? The other option I considered was to pull the values out in the `write_tags` method and then place them back after `form_to_metadata`.

2024-10-04 04:21 UTC, lordwelch requested changes

2024-10-04 04:21 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +        md.overlay(self.metadata, mode=comicapi.merge.Mode.ADD_MISSING, merge_lists=False)
This doesn't account for when someone wants to remove something, how would I remove the title from a comic that already has one set

2024-10-04 21:11 UTC, mizaki commented
I knew there was a reason why I rejected that way initially...

I've left it in the `form_to_metadata` method because `apply_cbl_transform` and `auto_imprint` could also wipe those values. Other instances of `form_to_metadata` shouldn't make a difference.

As the tag plugins now (I believe all?) receive the initial read data, it might be better to add `price` and `identifier` to the GUI and remove `is_version_of`, `rights` and `last_mark` from `GenericMetadata` (as a separate PR)?

2024-10-12 03:42 UTC, lordwelch requested changes

2024-10-12 03:42 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +
```suggestion

        # Preserve hidden md values
        md.origin = self.metadata.data_origin
        md.issue_id = self.metadata.issue_id
        md.series_id = self.metadata.series_id

        md.price = self.metadata.price
        md.identifier = self.metadata.identifier
        md.rights = self.metadata.rights

```

2024-10-12 03:42 UTC, lordwelch commented on comictaggerlib/taggerwindow.py
> +
```suggestion
```

2024-10-15 15:58 UTC, lordwelch approved these changes

2024-10-19 21:01 UTC, merged